name: Run Sitemap Parser

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час
  workflow_dispatch:      # Позволяет запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run parser
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # Секрет из настроек GitHub
        run: python main.py
